// Page Context Actions
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// Basic Content Actions
export const REQUESTING_CONTENT = 'REQUESTING_CONTENT';
export const RECEIVED_CONTENT = 'RECEIVED_CONTENT';

// Event Actions
export const REQUESTING_LATEST_EVENT_DETAILS = 'REQUESTING_LATEST_EVENT_DETAILS';
export const RECEIVED_LATEST_EVENT_DETAILS = 'RECEIVED_LATEST_EVENT_DETAILS';
export const RECEIVED_GROUP_INFORMATION = 'RECEIVED_GROUP_INFORMATION';

// Group Registrations
export const SAVING_GROUP_REGISTRATION = 'SAVING_GROUP_REGISTRATION';
export const ERROR_SAVING_GROUP_REGISTRATION = 'ERROR_SAVING_GROUP_REGISTRATION';
export const SAVED_GROUP_REGISTRATION = 'SAVED_GROUP_REGISTRATION';
export const SAVING_LEADER_PAYMENT_DETAILS = 'SAVING_LEADER_PAYMENT_DETAILS';
export const ERROR_SAVING_LEADER_PAYMENT_DETAILS = 'ERROR_SAVING_LEADER_PAYMENT_DETAILS';
export const SAVED_LEADER_PAYMENT_DETAILS = 'SAVED_LEADER_PAYMENT_DETAILS';
export const RESET_GROUP_REGISTRATION = 'RESET_GROUP_REGISTRATION';

// Individual Registrations
export const SAVING_INDIVIDUAL_REGISTRATION = 'SAVING_INDIVIDUAL_REGISTRATION';
export const ERROR_SAVING_INDIVIDUAL_REGISTRATION = 'ERROR_SAVING_INDIVIDUAL_REGISTRATION';
export const SAVED_INDIVIDUAL_REGISTRATION = 'SAVED_INDIVIDUAL_REGISTRATION';
export const SAVING_INDIVIDUAL_PAYMENT_DETAILS = 'SAVING_INDIVIDUAL_PAYMENT_DETAILS';
export const ERROR_SAVING_INDIVIDUAL_PAYMENT_DETAILS = 'ERROR_SAVING_INDIVIDUAL_PAYMENT_DETAILS';
export const SAVED_INDIVIDUAL_PAYMENT_DETAILS = 'SAVED_INDIVIDUAL_PAYMENT_DETAILS';
export const RESET_INDIVIDUAL_REGISTRATION = 'RESET_INDIVIDUAL_REGISTRATION';
