// Page Context Actions
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';

// Basic Content Actions
export const REQUESTING_CONTENT = 'REQUESTING_CONTENT';
export const RECEIVED_CONTENT = 'RECEIVED_CONTENT';

// Event Actions
export const REQUESTING_LATEST_EVENT_DETAILS = 'REQUESTING_LATEST_EVENT_DETAILS';
export const RECEIVED_LATEST_EVENT_DETAILS = 'RECEIVED_LATEST_EVENT_DETAILS';
